mybatis:
   #mapper文件路径
   mapper-locations: classpath:mapper/*Mapper.xml

   #实体类别名(不用在xml写实体类包名)
   type-aliases-package: com.mjw.baseutil.business.entity
spring:
   datasource:
      type: com.alibaba.druid.pool.DruidDataSource



